#!/bin/sh
#
# Master of Puppets — Vulkan Backend
# compile.sh — Compile GLSL shaders to SPIR-V and embed as C arrays
#
# Usage: ./compile.sh
# Requires: glslc (from shaderc / Vulkan SDK)
#
# Outputs: ../vulkan_shaders.h with static const uint32_t arrays
#
# SPDX-License-Identifier: Apache-2.0

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/.."
OUT_FILE="$OUT_DIR/vulkan_shaders.h"

# Check for glslc
if ! command -v glslc >/dev/null 2>&1; then
    echo "ERROR: glslc not found. Install shaderc or Vulkan SDK." >&2
    exit 1
fi

TMPDIR="${TMPDIR:-/tmp}"

compile_shader() {
    local src="$1"
    local array_name="$2"
    local spv="$TMPDIR/mop_$$_$(basename "$src").spv"

    echo "  Compiling $src -> $array_name"
    glslc -O "$src" -o "$spv"

    echo "static const uint32_t ${array_name}[] = {" >> "$OUT_FILE"

    # Convert binary SPIR-V to C hex array
    xxd -i < "$spv" | \
        sed 's/0x\([0-9a-f]\{2\}\), 0x\([0-9a-f]\{2\}\), 0x\([0-9a-f]\{2\}\), 0x\([0-9a-f]\{2\}\)/0x\4\3\2\1/g' \
        >> "$OUT_FILE"

    echo "};" >> "$OUT_FILE"
    echo "static const size_t ${array_name}_size = sizeof(${array_name});" >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"

    rm -f "$spv"
}

# Write header
cat > "$OUT_FILE" << 'HEADER'
/*
 * Master of Puppets — Vulkan Backend
 * vulkan_shaders.h — Pre-compiled SPIR-V shader bytecode
 *
 * AUTO-GENERATED by shaders/compile.sh — do not edit manually.
 * Re-generate: cd shaders && ./compile.sh
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef MOP_VK_SHADERS_H
#define MOP_VK_SHADERS_H

#include <stddef.h>
#include <stdint.h>

HEADER

echo "Compiling GLSL 450 -> SPIR-V -> C arrays..."

compile_shader "$SCRIPT_DIR/mop_solid.vert"     "mop_solid_vert_spv"
compile_shader "$SCRIPT_DIR/mop_solid.frag"      "mop_solid_frag_spv"
compile_shader "$SCRIPT_DIR/mop_wireframe.frag"  "mop_wireframe_frag_spv"

echo "#endif /* MOP_VK_SHADERS_H */" >> "$OUT_FILE"

echo "Done: $OUT_FILE"
