#!/bin/sh
#
# Master of Puppets — Vulkan Backend
# compile.sh — Compile GLSL shaders to SPIR-V and embed as C arrays
#
# Usage: ./compile.sh
# Requires: glslc (from shaderc / Vulkan SDK)
#
# Outputs: ../vulkan_shaders.h with static const uint32_t arrays
#
# SPDX-License-Identifier: Apache-2.0

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/.."
OUT_FILE="$OUT_DIR/vulkan_shaders.h"

# Check for glslc
if ! command -v glslc >/dev/null 2>&1; then
    echo "ERROR: glslc not found. Install shaderc or Vulkan SDK." >&2
    exit 1
fi

TMPDIR="${TMPDIR:-/tmp}"

compile_shader() {
    local src="$1"
    local array_name="$2"
    local spv="$TMPDIR/mop_$$_$(basename "$src").spv"

    echo "  Compiling $src -> $array_name"
    if ! glslc -O "$src" -o "$spv"; then
        echo "  WARNING: failed to compile $src (skipping)"
        return 1
    fi

    echo "static const uint32_t ${array_name}[] = {" >>"$OUT_FILE"

    # Convert binary SPIR-V to C hex array
    xxd -i <"$spv" |
        sed 's/0x\([0-9a-f]\{2\}\), 0x\([0-9a-f]\{2\}\), 0x\([0-9a-f]\{2\}\), 0x\([0-9a-f]\{2\}\)/0x\4\3\2\1/g' \
            >>"$OUT_FILE"

    echo "};" >>"$OUT_FILE"
    echo "static const size_t ${array_name}_size = sizeof(${array_name});" >>"$OUT_FILE"
    echo "" >>"$OUT_FILE"

    rm -f "$spv"
}

# Write header
cat >"$OUT_FILE" <<'HEADER'
/*
 * Master of Puppets — Vulkan Backend
 * vulkan_shaders.h — Pre-compiled SPIR-V shader bytecode
 *
 * AUTO-GENERATED by shaders/compile.sh — do not edit manually.
 * Re-generate: cd shaders && ./compile.sh
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef MOP_VK_SHADERS_H
#define MOP_VK_SHADERS_H

#include <stddef.h>
#include <stdint.h>

HEADER

echo "Compiling GLSL 450 -> SPIR-V -> C arrays..."

compile_shader "$SCRIPT_DIR/mop_solid.vert" "mop_solid_vert_spv"
compile_shader "$SCRIPT_DIR/mop_instanced.vert" "mop_instanced_vert_spv"
compile_shader "$SCRIPT_DIR/mop_solid.frag" "mop_solid_frag_spv"
compile_shader "$SCRIPT_DIR/mop_wireframe.frag" "mop_wireframe_frag_spv"
compile_shader "$SCRIPT_DIR/mop_shadow.vert" "mop_shadow_vert_spv"
compile_shader "$SCRIPT_DIR/mop_shadow.frag" "mop_shadow_frag_spv"
compile_shader "$SCRIPT_DIR/mop_fullscreen.vert" "mop_fullscreen_vert_spv"
compile_shader "$SCRIPT_DIR/mop_fxaa.frag" "mop_fxaa_frag_spv"
compile_shader "$SCRIPT_DIR/mop_tonemap.frag" "mop_tonemap_frag_spv"
compile_shader "$SCRIPT_DIR/mop_skybox.frag" "mop_skybox_frag_spv"
compile_shader "$SCRIPT_DIR/mop_overlay.frag" "mop_overlay_frag_spv"
compile_shader "$SCRIPT_DIR/mop_grid.frag" "mop_grid_frag_spv"
compile_shader "$SCRIPT_DIR/mop_bloom_extract.frag" "mop_bloom_extract_frag_spv"
compile_shader "$SCRIPT_DIR/mop_bloom_blur.frag" "mop_bloom_blur_frag_spv"
compile_shader "$SCRIPT_DIR/mop_bloom_upsample.frag" "mop_bloom_upsample_frag_spv"
compile_shader "$SCRIPT_DIR/mop_ssao.frag" "mop_ssao_frag_spv"
compile_shader "$SCRIPT_DIR/mop_ssao_blur.frag" "mop_ssao_blur_frag_spv"
compile_shader "$SCRIPT_DIR/mop_gtao.frag" "mop_gtao_frag_spv"
compile_shader "$SCRIPT_DIR/mop_gtao_blur.frag" "mop_gtao_blur_frag_spv"
compile_shader "$SCRIPT_DIR/mop_solid_bindless.vert" "mop_solid_bindless_vert_spv"
compile_shader "$SCRIPT_DIR/mop_solid_bindless.frag" "mop_solid_bindless_frag_spv"
compile_shader "$SCRIPT_DIR/mop_wireframe_bindless.frag" "mop_wireframe_bindless_frag_spv"
compile_shader "$SCRIPT_DIR/mop_cull.comp" "mop_cull_comp_spv"
compile_shader "$SCRIPT_DIR/mop_hiz_downsample.comp" "mop_hiz_downsample_comp_spv"
compile_shader "$SCRIPT_DIR/mop_taa.frag" "mop_taa_frag_spv"
compile_shader "$SCRIPT_DIR/mop_ssr.frag" "mop_ssr_frag_spv"
compile_shader "$SCRIPT_DIR/mop_oit_accum.frag" "mop_oit_accum_frag_spv"
compile_shader "$SCRIPT_DIR/mop_oit_composite.frag" "mop_oit_composite_frag_spv"
compile_shader "$SCRIPT_DIR/mop_decal.vert" "mop_decal_vert_spv"
compile_shader "$SCRIPT_DIR/mop_decal.frag" "mop_decal_frag_spv"
compile_shader "$SCRIPT_DIR/mop_volumetric.frag" "mop_volumetric_frag_spv"

# Mesh shading (Phase 10) — requires VK_EXT_mesh_shader / GLSL 450 + GL_EXT_mesh_shader
# glslc uses file extensions to determine shader stage: .task and .mesh
# These may fail on toolchains without mesh shader support — skip gracefully.
HAS_MESH=1
compile_shader "$SCRIPT_DIR/mop_meshlet.task" "mop_meshlet_task_spv" || HAS_MESH=0
compile_shader "$SCRIPT_DIR/mop_meshlet.mesh" "mop_meshlet_mesh_spv" || HAS_MESH=0

echo "" >>"$OUT_FILE"
echo "/* Feature flags: define these to enable shader-dependent pipelines */" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_SHADOW_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_POSTPROCESS_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_TONEMAP_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_SKYBOX_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_OVERLAY_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_BLOOM_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_SSAO_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_BINDLESS_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_CULL_SHADER 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_TAA_SHADER 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_SSR_SHADER 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_OIT_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_GTAO_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_DECAL_SHADERS 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_VOLUMETRIC_SHADER 1" >>"$OUT_FILE"
echo "#define MOP_VK_HAS_HIZ_SHADER 1" >>"$OUT_FILE"
if [ "$HAS_MESH" = "1" ]; then
    echo "#define MOP_VK_HAS_MESH_SHADERS 1" >>"$OUT_FILE"
fi
echo "" >>"$OUT_FILE"

echo "#endif /* MOP_VK_SHADERS_H */" >>"$OUT_FILE"

echo "Done: $OUT_FILE"
